import "./globals.css";
import { Inter } from "next/font/google";
import { Nunito } from 'next/font/google';
import Login from "./login/page";

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: "Turbo",
  description: "Generated by RootDevs",
};

export default function RootLayout({ children }) {


  


  return (
    <html lang="en">
      <body className={font.className}>
        {/* <div>
          <Login />
        </div> */}
        {children}
      </body>
    </html>
  );
}
